---

- name: Make sure swapfile physicaly exists.
  command: "dd if=/dev/zero of={{ swap_path }} bs={{ swap_dd_bs }}M count={{ swap_dd_count }} creates={{ swap_path }}"
  register: dd

- name: Make sure swapfile has proper permissions.
  file:
    path: "{{ swap_path }}"
    mode: "600"

- name: Make sure there is swap area.
  command: "mkswap {{ swap_path }}"
  register: mkswap
  when: dd.changed

- name: Make sure swapfile enabled.
  command: "swapon {{ swap_path }}"
  when: mkswap.changed

- name: Make sure swapfile in "/etc/fstab".
  lineinfile:
    dest: /etc/fstab
    line: '{{ swap_path }}   none    swap    sw    0   0'
    state: present

- name: Make sure "vm.swappiness" configured.
  lineinfile:
    dest: /etc/sysctl.conf
    line: 'vm.swappiness = {{ swap_swappiness }}'
    regexp: '^vm.swappiness[\s]?='
    state: present
  notify: sysctl
  when: swap_swappiness != false

- name: Make sure "vfs_cache_pressure" configured.
  lineinfile:
    dest: /etc/sysctl.conf
    line: 'vm.vfs_cache_pressure = {{ swap_vfs_cache_pressure }}'
    regexp: '^vm.vfs_cache_pressure[\s]?='
    state: present
  notify: sysctl
  when: swap_vfs_cache_pressure != false
