---

- name: Make sure swapfile physicaly exists.
  command: "dd if=/dev/zero of={{ swap_path }} bs={{ swap_dd_bs }}M count={{ swap_dd_count }} creates={{ swap_path }}"
  register: dd

- name: Make sure swapfile has proper permissions.
  file:
    path: "{{ swap_path }}"
    mode: 600

- name: Make sure there is swap area.
  command: "mkswap {{ swap_path }}"
  register: mkswap
  when: dd.changed

- name: Make sure swapfile enabled.
  command: "swapon {{ swap_path }}"
  when: mkswap.changed

- name: Make sure swapfile in "/etc/fstab".
  lineinfile:
    dest: /etc/fstab
    line: '{{ swap_path }}   none    swap    sw    0   0'
    state: present

- name: Make sure swap-related sysctl options are set.
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - name: vm.swappiness
      value: "{{ swap_swappiness }}"
    - name: vm.vfs_cache_pressure
      value: "{{ swap_vfs_cache_pressure }}"
